name: tictacgo
description: "A cross-platform Tic Tac Toe game featuring Minimax AI, P2P local discovery, and real-time online multiplayer using Material 3."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter  
  flutter_riverpod: ^2.5.1
  hive_ce: ^2.0.0
  hive_ce_flutter: ^2.0.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.9.2
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
